version: '3.8'

services:
  backend:
    build: ./backend
    container_name: assisten-backend
    restart: unless-stopped
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=bpom_ai
      - DB_PASSWORD=SatXr75Y64kbDCaT
      - DB_NAME=bpom_ai
      - KEYCLOAK_SERVER_URL=http://localhost:8180
      - KEYCLOAK_REALM=master
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=ontageniT1!
      - NODE_ENV=production
      - PORT=5003
      - DATA_PATH=/data
      - LOGS_PATH=/data/logs
      - UPLOADS_PATH=/data/uploads
    volumes:
      - ./data/backend:/data
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # Tambahkan ini untuk memastikan uploads bisa diakses
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assisten-frontend
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://data-asissten.bbpompky.id/api
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/master
      - KEYCLOAK_CLIENT_ID=assistant
      - KEYCLOAK_CLIENT_SECRET=4GiUIh9Z5b6vXV4pBtheIunRMQvVJsuT
      - NEXTAUTH_URL=https://asisten-laura.bbpompky.id
      - NEXTAUTH_URL_INTERNAL=http://localhost:3004
      - NEXTAUTH_TRUST_HOST=true
      - NEXTAUTH_SECRET=dnpp//pRJuxPWuZsWUBX4YB0BAxORPt7dRR/MX91KEA=
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=ontageniT1!
      - DATA_PATH=/data
      - CACHE_PATH=/data/.next/cache
      - PUBLIC_UPLOADS_PATH=/data/public/uploads
    volumes:
      - ./data/frontend:/data
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"